---
on:
  push:
    branches:
      - main
    # Only run when there are changes in the src/ images
    paths:
      - "images/**"
  workflow_dispatch:
name: "Build and Push Images"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - default
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Image - ${{ matrix.image }}
        uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5 # v3.2.0
        with:
          push: true
          context: "./images/${{ matrix.image }}"
          tags: |
            ghcr.io/${{ github.repository }}:${{ matrix.image }}-latest
            ghcr.io/${{ github.repository }}:${{ matrix.image }}-${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ matrix.image }}-latest
          cache-to: type=inline
