---
on:
  push:
    branches:
      - main
    # Only run when there are changes in the src/ images
    paths:
      - "images/**"
  workflow_dispatch:
name: "Build and Push Images"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - default
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Image - ${{ matrix.image }}
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          push: true
          context: "./images/${{ matrix.image }}"
          tags: |
            ghcr.io/${{ github.repository }}/images/${{ matrix.image }}:latest
            ghcr.io/${{ github.repository }}/images/${{ matrix.image }}:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/images/${{ matrix.image }}:latest
          cache-to: type=inline
